version: "3.3"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u ${DB_USER} --password=${DB_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 6

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', '${WP_HOME}' );
        define( 'WP_SITEURL', '${WP_SITEURL}' );
        define( 'WP_DEBUG', ${WP_DEBUG} );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SCRIPT_DEBUG', ${WP_DEBUG} );
    volumes:
      - wordpress_data:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/${THEME_SLUG}
      - ./uploads:/var/www/html/wp-content/uploads
    extra_hosts:
      - "${HOST_DOMAIN}:127.0.0.1"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_USER: ${DB_USER}
  #     PMA_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "8081:80"

volumes:
  mysql_data:
  wordpress_data:
